[tool.mypy]
exclude = [
    "build",
    "dist",
    "venv",
    "integration_tests",
    "scripts",
    "tests",
    "playground",
]

ignore_missing_imports = true
explicit_package_bases = true
namespace_packages = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
disallow_any_generics = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true

mypy_path = ["."]
python_version = "3.13"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.ruff]
target-version = "py313"
line-length = 120
lint.select = ["E", "F", "W", "B"]
