name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  server-ci:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Install dependencies
        run: make server-init

      - name: Run linter
        run: make server-lint

      - name: Run type checker
        run: make server-type

      - name: Run tests
        run: make server-test
