name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "0.5.30"

      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt -r requirements-dev.txt --system

      - name: Run tests
        run: pytest -v

      - name: Run linter
        run: ruff check .

      - name: Run type checker
        run: mypy src
